# Generated by Django 5.0.5 on 2024-07-14 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_comment_post_comments_replay_comment_replies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Replay",
            new_name="Reply",
        ),
    ]
